[build.environment]
  NODE_VERSION = "18"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"

[build]
  command = "npm ci && npm rebuild sharp --platform=linux --arch=x64 && npm run build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000"
